-- Add migration script here
INSERT INTO team (name) VALUES ('Qatar');
INSERT INTO team (name) VALUES ('Angleterre');
INSERT INTO team (name) VALUES ('Argentine');
INSERT INTO team (name) VALUES ('France');
INSERT INTO team (name) VALUES ('Équateur');
INSERT INTO team (name) VALUES ('Iran');
INSERT INTO team (name) VALUES ('Arabie saoudite');
INSERT INTO team (name) VALUES ('Australie');
INSERT INTO team (name) VALUES ('Sénégal');
INSERT INTO team (name) VALUES ('États-Unis');
INSERT INTO team (name) VALUES ('Mexique');
INSERT INTO team (name) VALUES ('Danemark');
INSERT INTO team (name) VALUES ('Pays-Bas');
INSERT INTO team (name) VALUES ('Pays de Galles');
INSERT INTO team (name) VALUES ('Pologne');
INSERT INTO team (name) VALUES ('Tunisie');
INSERT INTO team (name) VALUES ('Espagne');
INSERT INTO team (name) VALUES ('Belgique');
INSERT INTO team (name) VALUES ('Brésil');
INSERT INTO team (name) VALUES ('Portugal');
INSERT INTO team (name) VALUES ('Costa Rica');
INSERT INTO team (name) VALUES ('Canada');
INSERT INTO team (name) VALUES ('Serbie');
INSERT INTO team (name) VALUES ('Ghana');
INSERT INTO team (name) VALUES ('Allemagne');
INSERT INTO team (name) VALUES ('Maroc');
INSERT INTO team (name) VALUES ('Suisse');
INSERT INTO team (name) VALUES ('Uruguay');
INSERT INTO team (name) VALUES ('Japon');
INSERT INTO team (name) VALUES ('Croatie');
INSERT INTO team (name) VALUES ('Cameroun');
INSERT INTO team (name) VALUES ('Corée du Sud');