name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install cargo cross
        run: cargo install cross

      - name: Install podman
        run: sudo apt-get -y install podman

      - name: Build
        run: cross build --release --target armv7-unknown-linux-gnueabihf

      - name: Create package
        run: tar -czvf soccer.tar.gz ./Rocket.toml -C ./target/armv7-unknown-linux-gnueabihf/release soccer_bet_api

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./soccer.tar.gz
          asset_name: soccer.tar.gz
          asset_content_type: application/x-compressed-tar
